project_id = "eymapbckavncyviworlh"

[functions.send-pod-configuration-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-newsletter-subscription]
verify_jwt = false